read_raw:
  _target_: mne.io.read_raw_brainvision
  eog: [64, 65]
  preload: False

raw_params:
  raw_extension: '.vhdr'
  line_freq: 60
  data_type: 'eeg'

preprocessing_params:
  l_freq: 0.1
  h_freq: 30.0
  l_trans_bandwidth: 'auto'
  h_trans_bandwidth: 'auto'
  filter_length: 'auto'
  method: 'fft'
  n_jobs: 1
